dictionnaire_extensions = {
    "TXT": "fichiers texte brut, sans mise en forme.",
    "DOC": "documents Word. Ce format est obsolète, car il appartient aux anciennes versions d'Office.",
    "DOCX": "format par défaut des documents Word. Ce format ne permet pas aux macros de s'exécuter.",
    "DOCM": "identique à DOCX, mais avec les macros activées.",
    "ODT": "document texte au format OpenDocument, idéal pour une utilisation avec des suites alternatives telles que "
           "LibreOffice.",
    "PDF": "format Adobe Acrobat. Protégez le style et évitez les modifications.",
    "RTF": "format texte riche, parfait pour le partage entre différents systèmes d'exploitation.",
    "CSV": "format ouvert pour représenter tout type de données sous forme de tableau.",
    "XLS": "documents Excel. Ce format est obsolète, car il appartient aux anciennes versions d'Office.",
    "XLSX": "format par défaut des documents Excel. Ce format ne permet pas aux macros de s'exécuter.",
    "XLSM": "identique à XLSX, mais avec les macros activées.",
    "ODS": "feuille de calcul au format OpenDocument, idéale pour une utilisation avec d'autres suites bureautiques "
           "telles que LibreOffice.",
    "PPS": "diaporama PowerPoint configuré pour toujours s'ouvrir en mode présentation. Ce format est obsolète, "
           "car il appartient aux anciennes versions d'Office.",
    "PPT": "diaporama PowerPoint. Ce format est obsolète, car il appartient aux anciennes versions d'Office.",
    "PPSX": "format PowerPoint par défaut pour ouvrir le fichier en mode présentation. Ce format ne permet pas aux "
            "macros de s'exécuter.",
    "PPTX": "format PowerPoint par défaut. Ce format ne permet pas aux macros de s'exécuter.",
    "PPSM": "identique à PPSX, mais avec des macros.",
    "PPTM": "identique à PPTX, mais avec des macros.",
    "POTX": "modèle Microsoft PowerPoint.",
    "ODP": "format OpenDocument pour le diaporama, idéal pour une utilisation avec d'autres suites bureautiques "
           "telles que LibreOffice.",
    "MP3": "codec musical standard avec compression.",
    "WMA": "format audio développé par Microsoft avec compression et DRM possible.",
    "WAV": "format audio numérique avec ou sans compression.",
    "FLAC": "format audio numérique haute fidélité et sans perte.",
    "MIDI": "protocole de transfert de données, avec informations sonores, 8 bits.",
    "OGG": "codec audio gratuit, très populaire comme alternative au MP3.",
    "AVI": "conteneur audio et vidéo pouvant contenir plusieurs flux de données audio et vidéo.",
    "DIVX": "format utilisé pour stocker des fichiers vidéo haute définition et de qualité.",
    "MOV": "format utilisé par QuickTime.",
    "MP4": "format capable de stocker du contenu multimédia tel que audio, vidéo et sous-titres.",
    "MPG": "format avec compression de perte de faible qualité.",
    "WMV": "format vidéo développé par Microsoft avec compression et DRM possible.",
    "JPEG": "format le plus utilisé dans les images numériques, avec compression et perte.",
    "JPG": "format le plus utilisé dans les images numériques, avec compression et perte.",
    "PNG": "format graphique avec compression sans perte. Prend en charge les transparents.",
    "BMP": "image bitmap.",
    "ICO": "fichier d'icônes.",
    "SVG": "image graphique vectorielle.",
    "WEBP": "format d'image de compression développé par Google pour le web.",
    "GIF": "images animées.",
    "PSD": "projet Adobe Photoshop.",
    "HEIC": "format d'image utilisé par Apple sur macOS et iOS.",
    "NEF": "format d'image brut, brut, utilisé par les appareils photo Nikon et Canon.",
    "CRW": "format d'image brut, brut, utilisé par les appareils photo Nikon et Canon.",
    "AI": "projet Adobe Ilustrator.",
    "ID": "projet Adobe InDesign.",
    "EXE": "exécutable Windows.",
    "LNK": "accès direct.",
    "BAT": "script pour CMD.",
    "COM": "application MS-DOS.",
    "PS1": "script PowerShell.",
    "DLL": "bibliothèques avec le code nécessaire au fonctionnement des programmes.",
    "MSI": "installateur.",
    "SYS": "fichiers système critiques. Il n'est pas recommandé de les toucher ou de les effacer.",
    "TTF": "police TrueType.",
    "OTF": "police OpenType.",
    "INI": "fichier de configuration.",
    "SCR": "protecteur d'écran.",
    "INF": "informations d'installation.",
    "BIN": "fichier binaire.",
    "ZIP": "format développé par WinZIP.",
    "RAR": "format de compression développé par WinRAR plus efficace que ZIP.",
    "RAR5": "version renouvelée de RAR avec améliorations de sécurité et récupération de données.",
    "7Z": "format gratuit développé par le créateur de 7-Zip.",
    "ISO": "format d'image par excellence.",
    "CUE": "les données du disque (telles que les pistes audio, les titres, la durée, etc.) sont enregistrées sous "
           "forme de fichiers texte en ASCII. Il contient les instructions pour lire le BIN ci-joint.",
    "IMG": "largement utilisé, par exemple, pour créer des copies littérales de cartes mémoire ou d'autres unités.",
    "HTML": "fichier texte avec code pour une page Web.",
    "CSS": "extension de style qui accompagne HTML.",
    "JS": "script JavaScript.",
    "PHP": "code PHP.",
    "EML": "format email.",
    "MSG": "format email."
}

dictionnaire_extensions_recherchable = {
    "PDF": True,
    "TXT": True,
    "MKV": True,
    "C": True,
    "INI": True,
    "IPYNB": True,
    "JPEG": True,
    "JPG": True,
    "MP4": True,
}
